info:
  component: Turbine

#PREFIX:
#endpoints:
#  restart:
#    enabled: true
#  shutdown:
#    enabled: true

server:
  port: ${PORT:8989}

management:
  port: 8990

logging:
  level: INFO

eureka:
  client:
    serviceUrl:
      defaultZone: ${vcap.services.${PREFIX:}eureka.credentials.uri:http://user:password@localhost:8761}/eureka/
  server:
    waitTimeInMsWhenSyncEmpty: 0
  instance:
    leaseRenewalIntervalInSeconds: 5

turbine:
  clusterNameExpression: new String("default")
#  aggregator:
#    clusterConfig: VOTING
  appConfig: api-composite-service
