info:
  component: support-monitor
endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
server:
  port: 7979
logging:
  level:
    ROOT: INFO
org.springframework.web: DEBUG
turbine:
  ##  Adding default metric cluster
  appConfig: COMPOSITE-SERVICE
  clusterNameExpression: new String("default")

  