# EMBEDDED SERVER CONFIGURATION
server:
    port: ${port:8080}
    context-path: /
    error.whitelabel.enabled: false
# PROFILES
spring:
    aop:
        proxyTargetClass: true
    application.name: shardis-ui
    profiles.active: prod
# EUREKA
eureka:
  instance:
    hostname: localhost
    port: 8081
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/
# ZULL
zuul:
  routes:
     shardis-api:
          sensitiveHeaders:
          path: /api/**
          stripPrefix: false
     shardis-auth:
          sensitiveHeaders:
          path: /auth/**
          stripPrefix: false
  add-proxy-headers: true
#SECURITY
security:
  basic:
    enabled: false
  oauth2:
    sso:
      loginPath: /login
    resource:
      jwt:
        keyValue: |
              -----BEGIN PUBLIC KEY-----
              MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAnGp/Q5lh0P8nPL21oMMrt2RrkT9AW5jgYwLfSUnJVc9G6uR3cXRRDCjHqWU5WYwivcF180A6CWp/ireQFFBNowgc5XaA0kPpzEtgsA5YsNX7iSnUibB004iBTfU9hZ2Rbsc8cWqynT0RyN4TP1RYVSeVKvMQk4GT1r7JCEC+TNu1ELmbNwMQyzKjsfBXyIOCFU/E94ktvsTZUHF4Oq44DBylCDsS1k7/sfZC2G5EU7Oz0mhG8+Uz6MSEQHtoIi6mc8u64Rwi3Z3tscuWG2ShtsUFuNSAFNkY7LkLn+/hxLCu2bNISMaESa8dG22CIMuIeRLVcAmEWEWH5EEforTg+QIDAQAB
              -----END PUBLIC KEY-----
      id: openid
      serviceId: ${PREFIX:}resource

# LOGGING
logging.level.org.springframework.security: DEBUG
